### PR TITLE
Shuttle schedule UI modification

### PR DESCRIPTION
**Pull request by JenYn**
The modifications were made as to enhance legibility of the shuttle bus schedule. 
The colours used were those of the official colour palette. 
Issue related to it: #135

### CODE REVIEW

**Comment by jaychenblue** [comment]
@JenYn Can you center everything? Like all the headers and times so that they're in the center of their columns. I think it would look even better that way.

**Comment by jaychenblue** [comment]
@vicmanea Why is 11:10 repeated twice in departures from Loyola (see the screenshot in my comment above)? What's the meaning of this? This is probably a bug.

**Comment by vicmanea** [comment]
> @vicmanea Why is 11:10 repeated twice in departures from Loyola (see the screenshot in my comment above)? What's the meaning of this? This is probably a bug.

It seems to be an oversight in the hard-coding of the times. It should say 11:30. This will be fixed

**Comment by JenYn** [comment]
> @JenYn Can you center everything? Like all the headers and times so that they're in the center of their columns. I think it would look even better that way.

I will center everything and make another pull request.

**Comment by JenYn** [comment]
@jaychenblue @vicmanea the times are now centered. I also fixed the duplicate time in the last commit. Ready to be merged.

**Comment by jaychenblue** [comment]
Screen Shot 2020-03-15 at 2 12 34 PM

Looks fantastic.

**Pull request merged**
