### PR TITLE
Added Espresso tests for user stories implemented in sprint 1 and 2

### PR DESCRIPTION
**Pull request by vincentcerri**
Need to merge the espresso tests onto the master branch.

### CODE REVIEW

**Comment by jaychenblue** [comment]
@vincentcerri Are you going to handle system tests?

I have a few questions:
- Is Espresso basically automated system tests, i.e. it automates the process of interacting with the user interface of the app?
- Is the test code generated by Espresso or did you write them yourself?

**Comment by vincentcerri** [comment]
@jaychenblue 
Yes espresso is included in Android Studio and it is an automated way to perform system tests. All you have to do is click on record espresso test and you will perform the actions that you want to test with the emulator. Once done, you can stop the test and the code for the test will be automatically generated. All you have to do is save the file with a test name that represents the test you performed. 

It would be best if we all did them as they are quite simple to do.

**Comment by JYSW380** [comment]
@vincent for commits please follow our development guidelines:

-Make sure your commit messages are descriptive -- this means anyone reading your commit should easily understand what was done
-Make sure your commit messages reference the appropriate GitHub issue number, like so:
`git commit -m "[#145] Add test to check insert method"`

**Comment by jaychenblue** [comment]
> @vincent for commits please follow our development guidelines:
> 
> -Make sure your commit messages are descriptive -- this means anyone reading your commit should easily understand what was done
> -Make sure your commit messages reference the appropriate GitHub issue number, like so:
> `git commit -m "[#145] Add test to check insert method"`

I think it's fine for this pull request. In general, we should definitely respect the development guidelines outlined in the wiki.

**Comment by jaychenblue** [comment]
The test "BY14_AdditionalInfo" fails with a bunch of error messages.

Even for the tests that pass, the emulator seems buggy and closes by itself (but the test says it passed).

@vincentcerri Is this expected?

**Comment by JYSW380** [comment]
For "BY14_AdditionalInfo" I got the following error message `androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: com.example.scoutconcordia:id/directionsButton and with text: is "Get Directions" and Child at position 0 in parent Child at position 4 in parent with class name: is "android.widget.RelativeLayout" and is displayed on the screen to the user)
If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews:com.google.maps.api.android.lib6.impl.ck{20664790 G.ED..C. ......I. 0,0-0,0}`

**Comment by jaychenblue** [comment]
These issues need to be resolved before merging into master. I'll discuss with @vincentcerri on possible next steps.

**Pull request closed without merging**
