### PR TITLE
Adding nodes

### PR DESCRIPTION
**Pull request by vincentcerri**
This branch was created to improve the performance of issue #141 .

To improve the performance, more nodes we added to Hall 1st floor and Hall 2nd floor so that the breadth first search can perform better. The issue we were facing originally was that while performing the search, a path was not being formed due to a lack of nodes along the way and causing the app to crash.

**Acceptance criteria:** 
- [ ] Be able to get directions to any classroom on either Hall 1st floor or 2nd floor.

### CODE REVIEW

**Comment by vincentcerri** [comment]
> When I run it on my emulator, I see two different sets of toggles
> image
> 
> I'm running it on the Pixel 2 XL API 29

I have downloaded the same emulator version as mentioned while running your tests however I am not coming up with the same results. The buttons for the floor selection appear to be in the correct position for me. If this issue keeps appearing, we can edit it more in issue #226 as we are still currently making changes to the format of these buttons. 

image

**Comment by JenYn** [comment]
I don't see the toggles anymore:
image


Great work!!

**Comment by jaychenblue** [comment]
@vincentcerri This PR only improves the performance of the first and second floors of Hall. For the scope of this project, are these the only floors that work reliably?

**Comment by jaychenblue** [comment]
The performance is smooth and works as expected. I'm able to find directions to the first and second floors of Hall without issue.

**Pull request merged**
