### PR TITLE
[#207] Refactor equals method in Graph.java

### PR DESCRIPTION
**Pull request by JenYn**
Based on SonarQube's analysis, we need to refactor equals methods in the Graph.java file. 

This is related to issue #209 

Note: I ran the app and tried to navigate between two classes, and it works. However, In order to know if the code is now fully compliant, I would need to merge it to master and run an analysis again since we unfortunately cannot analyze branches unless we have the paid version of SonarQube.

### CODE REVIEW

**Comment by jaychenblue** [comment]
@JenYn This PR has old code that was reverted by @vicmanea. Once his PR is merged, pull the latest changes from master.

**Comment by jaychenblue** [comment]
@JenYn When refactoring code, can you run all unit tests to ensure that everything still works as expected? Post your results here (e.g. all unit tests pass).

**Comment by JenYn** [comment]
> @JenYn When refactoring code, can you run all unit tests to ensure that everything still works as expected? Post your results here (e.g. all unit tests pass).

Very good point. Didn't think of that.
I ran all unit tests and all 33 passed:
image
image


However, when running the Espresso tests, all pass except for "BY_14AdditionalInfo". 
When I ran the same test on the master branch, however, I got the same error:
image

**Comment by jaychenblue** [comment]
@JenYn The master branch has been updated. Please pull the latest changes and try running the unit tests again.

**Pull request closed without merging**
