### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Averynder**
Includes first test to just swap between campus' and the libraries needed to run them in the build file

### CODE REVIEW

**Comment by jaychenblue** [comment]
Why do the markers turn into smiley faces when clicked on? Is this just a temporary thing during the implementation process?

image

**Comment by Averynder** [comment]
> 
> 
> Why do the markers turn into smiley faces when clicked on? Is this just a temporary thing during the implementation process?
> 
> image

It's temporary to display just the listener for clicking as well as replacing the default picture with a custom one

**Comment by jaychenblue** [comment]
OK, sounds good. It works on my end so I'm going to approve this.

**Comment by jaychenblue** [comment]
By the way, there's a conflict in the app/build.gradle file according to GitHub.

**Comment by JYSW380** [comment]
After i clicked the building, there are two buttons in the information pop up page, and do nothing after i clicking on it. Except that, looks good to me.
Screen Shot 2020-02-28 at 2 02 53 PM

**Comment by jaychenblue** [comment]
Screen Shot 2020-02-29 at 9 27 23 PM

**Pull request merged**
