### PR TITLE
Jacoco plugin to generate coverage reports

### PR DESCRIPTION
**Pull request by JenYn**
JaCoCo is a free code coverage library for Java.

This configuration only works on Windows. If you have a mac, it will not work.

To generate the test coverage report, run the following command in the terminal:
./gradlew jacocoTestReportDebug

The report will be found here: scout-concordia\app\build\reports\jacoco\debug\index.html

Related to issue #158

### CODE REVIEW

**Comment by JenYn** [comment]
> Gradle sync failed. The project no longer works on my computer (macOS) due to the changed Java home value (see photo below).
> 
> @JenYn Does this branch work on your computer running macOS?
> 
> Also, please pull the latest changes from master and resolve the merge conflicts for this branch.
> 
> Screen Shot 2020-03-28 at 2 06 54 PM

No, This only works on Windows.

**Comment by jaychenblue** [comment]
If this only works on Windows, merging this pull request in its current state will prevent most of the collaborators from working on the project.

**Comment by JenYn** [comment]
You are right. We could not find a solution for MacOS. We followed a lot of tutorials and looked at a lot of documentation and were only able to get the reports last night with the help of the TA. 

I will close this PR and we will have @vincentcerri run the command to generate the report. This will be fixed during Sprint 4 so that it works on both MacOS and Windows. 
What do you think?

**Comment by jaychenblue** [comment]
Sounds good. When JaCoCo works on both macOS and Windows, then we can merge it into master. In its current state, we can keep this as a separate branch and have someone on Windows to generate the testing report.

@JenYn Close this PR and make sure to keep the jacoco-setup-v2 branch up to date with master.

**Pull request closed without merging**
