### PR TITLE
Directions to a schedule event

### PR DESCRIPTION
**Pull request by ManpreetSohal**
User clicks on an event in the schedule and clicks on the "Go" button. User is taken to the MapsActivity and is asked to input the starting location and select mode of travel. Directions are displayed on getDirections button click. If event location is invalid, a message is displayed indicating it.

1. User clicks on an event
image

2. user clicks on "Go"
   a. Location is valid
image

  b. Location is invalid
image

3. User clicks on getDirections button
image

### CODE REVIEW

**Comment by JenYn** [comment]
I tried running it and I do not see any events anymore. 
image

**Comment by JenYn** [comment]
> I tried running it and I do not see any events anymore.
> image

### Trying with valid location
After closing Android studio and the emulator, and running it again, it works.
image

image
image

image

**Comment by JenYn** [comment]
### Testing with invalid location
image

image


Suggestion 1: We can maybe make the message a bit bigger so the users don't miss it?
Suggestion 2: I could add a section in settings telling users the format in which classes should be written and we just tell the users to check the settings page for suggestions.

**Comment by jaychenblue** [comment]
@JenYn The first suggestion is up to @ManpreetSohal. Making the message bubble bigger would be a nice visual improvement for the user.

The second suggestion can be done in the menu section.

**Comment by ManpreetSohal** [comment]
@JenYn @jaychenblue I think for now we can leave it as is and focus on tasks with higher priority. We can enhance visual details later after we are done with more important tasks as we only have a limited amount left to wrap up. If you guys feel otherwise, I'll be more than happy to work on it now.

**Comment by jaychenblue** [comment]
Sounds good. We're good to go.

**Pull request merged**
