### PR TITLE
Adding the shuttle route estimate to the main application

### PR DESCRIPTION
**Pull request by vicmanea**
[#156] Adding the shuttle route estimate to the main application

### CODE REVIEW

**Comment by vicmanea** [comment]
Screen Shot 2020-04-14 at 6 21 57 PM

The app successfully pulls the next shuttle time and calculates a route estimate.

**Comment by vicmanea** [comment]
> The estimates given don't match when the shuttle option is selected (in the example below, 31.8 minutes vs. 86 minutes).
> 
> Also, the next shuttle time and shuttle route estimate should **_only_** be displayed when the user selects the shuttle option (and thus should NOT be displayed when walking/car/transit is chosen).
> 
> Screenshot_1586903306

The pre-existing code seems to merge the bus and shuttle conditions. So we have to find a way to overlap them or make the bus disappear when the user selects Shuttle. I'm working on it now.

**Comment by vicmanea** [comment]
> The estimates given don't match when the shuttle option is selected (in the example below, 31.8 minutes vs. 86 minutes).
> 
> Also, the next shuttle time and shuttle route estimate should **_only_** be displayed when the user selects the shuttle option (and thus should NOT be displayed when walking/car/transit is chosen).
> 
> Screenshot_1586903306

In the newest push, the Shuttle Estimate will not appear when the user selects the Driving or Walking option. However it does appear at the Bus or Shuttle options.

**Comment by jaychenblue** [comment]
The shuttle estimate doesn't show when the shuttle option is selected (see picture below). It does show when the public transit option is selected. I understand that there's some kind of link between the two modes, but the next shuttle time and shuttle estimate should be displayed when the shuttle option is selected.

Screenshot_1587151349

**Comment by ManpreetSohal** [comment]
> The shuttle estimate doesn't show when the shuttle option is selected (see picture below). It does show when the public transit option is selected. I understand that there's some kind of link between the two modes, but the next shuttle time and shuttle estimate should be at least be displayed when the shuttle option is selected (even if it also displays when the public transit mode is selected).
> 
> Screenshot_1587151349

Shuttle time and route are now displayed as intended.

**Pull request merged**
